"""定数定義モジュール"""

# 発注提案ステータス（逆遷移不可）
PROPOSAL_STATUS_GENERATED = "生成"
PROPOSAL_STATUS_REVIEWING = "確認中"
PROPOSAL_STATUS_APPROVED = "承認"
PROPOSAL_STATUS_REJECTED = "却下"

PROPOSAL_STATUSES = [
    PROPOSAL_STATUS_GENERATED,
    PROPOSAL_STATUS_REVIEWING,
    PROPOSAL_STATUS_APPROVED,
    PROPOSAL_STATUS_REJECTED,
]

# 許可される遷移パス
PROPOSAL_TRANSITIONS = {
    PROPOSAL_STATUS_GENERATED: [PROPOSAL_STATUS_REVIEWING],
    PROPOSAL_STATUS_REVIEWING: [PROPOSAL_STATUS_APPROVED, PROPOSAL_STATUS_REJECTED],
    PROPOSAL_STATUS_APPROVED: [],
    PROPOSAL_STATUS_REJECTED: [],
}

# 配送ステータス（逆遷移不可）
DELIVERY_STATUS_PENDING = "未配送"
DELIVERY_STATUS_IN_TRANSIT = "配送中"
DELIVERY_STATUS_COMPLETED = "配送完了"

DELIVERY_STATUSES = [
    DELIVERY_STATUS_PENDING,
    DELIVERY_STATUS_IN_TRANSIT,
    DELIVERY_STATUS_COMPLETED,
]

DELIVERY_TRANSITIONS = {
    DELIVERY_STATUS_PENDING: [DELIVERY_STATUS_IN_TRANSIT],
    DELIVERY_STATUS_IN_TRANSIT: [DELIVERY_STATUS_COMPLETED],
    DELIVERY_STATUS_COMPLETED: [],
}

# 発注予定ステータス（逆遷移不可）
ORDER_PLAN_STATUS_PENDING = "未発注"
ORDER_PLAN_STATUS_EXECUTED = "発注済み"

ORDER_PLAN_STATUSES = [
    ORDER_PLAN_STATUS_PENDING,
    ORDER_PLAN_STATUS_EXECUTED,
]

ORDER_PLAN_TRANSITIONS = {
    ORDER_PLAN_STATUS_PENDING: [ORDER_PLAN_STATUS_EXECUTED],
    ORDER_PLAN_STATUS_EXECUTED: [],
}

# ロール
ROLE_MANAGER = "MANAGER"
ROLE_DRIVER = "DRIVER"

# バリデーション
ORDER_QUANTITY_MIN = 1
ORDER_QUANTITY_MAX = 10000

# キャッシュTTL（秒）
CACHE_TTL_DASHBOARD = 300  # 5分
CACHE_TTL_MASTER = 3600  # 1時間
CACHE_TTL_AUTH = 300  # 5分（ロール変更の即時反映とのバランス）

# プライバシーポリシー
CURRENT_POLICY_VERSION = "1.0.0"
